### PR TITLE
clarify the requirements to move out of sandbox

### PR DESCRIPTION
**Pull request by tomerd**
motivation: with projects beginning to mature, clarify the requirements to move out of sandbox

changes: add language about contribution requirements for sandbox -> incubating

### CODE REVIEW

**Review by weissi — APPROVED** [review]
thank you, looks good to me!

**Comment by tomerd** [comment]
@tanner0101 @loganwright

**Review by ktoso — APPROVED** [review]
Definition of committer sounds good 👍

**Review by tanner0101 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
