### PR TITLE
Update proposal with the upload streaming comments

### PR DESCRIPTION
**Pull request by artemredkin**

### CODE REVIEW

**Comment by tomerd** [comment]
@artemredkin is this ready to be merged?

**Comment by tomerd** [comment]
pinging @artemredkin

**Review by weissi — APPROVED** [review]

**Comment by artemredkin** [comment]
This proposal is slightly out of date (we changed things after), should I update it to the latest version or should we merged it like it was pitched originally?

**Comment by Mordil** [comment]
*puts on my technical writer hat*

I'd say leave most of this as it was when the proposal was accepted, but perhaps add a note in the relevant sections to PRs where things might have significantly changed.

**Comment by tomerd** [comment]
@artemredkin feel free to submit future PRs to address any inconsistencies you think are important to address or noted

**Pull request merged**
