### PR TITLE
add language about sswg membership

### PR DESCRIPTION
**Pull request by tomerd**
motivation: add transperancy around how sswg membership works

changes: add "Membership" section to the main readme

### CODE REVIEW

**Review by tanner0101 — APPROVED** [review]
LGTM. I added some small grammar tweaks. I meant to put that as a separate PR, but pushed it to your branch by accident. Let me know if you want me to undo that or if it looks fine.

**Comment by tanner0101** [comment]
After this is merged, may we should set a max line length for the markdown? Entire paragraphs being in a single line makes GitHub diffs pretty useless.

**Comment by tomerd** [comment]
thanks @tanner0101

**Review by ianpartridge — APPROVED** [review]
Seems very sensible to me.  Thanks @tomerd

**Review by weissi — APPROVED** [review]
👍

**Pull request merged**
